# Generated by Django 3.1 on 2023-05-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20230508_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='guest_user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_guest_user',
        ),
    ]
