# Generated by Django 3.1 on 2023-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_heroimages_hero_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimages',
            name='herotitle_position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
