# Generated by Django 3.1 on 2023-02-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20230215_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimages',
            name='hero_link_state',
            field=models.CharField(default='on', max_length=200),
        ),
    ]
