# Generated by Django 3.1 on 2023-05-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20230508_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_guest_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
